//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.14 at 12:01:19 p. m. CET 
//


package com.ucm.shiro.facturae.v3_0.parser.types;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PaymentDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssignmentDuePaymentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AssignmentPaymentMeans" type="{http://www.facturae.es/Facturae/2007/v3.0/Facturae}TextMax15Type"/>
 *         &lt;element name="IBAN" type="{http://www.facturae.es/Facturae/2007/v3.0/Facturae}TextMin5Max34Type"/>
 *         &lt;element name="PaymentReference" type="{http://www.facturae.es/Facturae/2007/v3.0/Facturae}TextMax60Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentDetailsType", propOrder = {
    "assignmentDuePaymentDate",
    "assignmentPaymentMeans",
    "iban",
    "paymentReference"
})
public class PaymentDetailsType {

    @XmlElement(name = "AssignmentDuePaymentDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar assignmentDuePaymentDate;
    @XmlElement(name = "AssignmentPaymentMeans", required = true)
    protected String assignmentPaymentMeans;
    @XmlElement(name = "IBAN", required = true)
    protected String iban;
    @XmlElement(name = "PaymentReference", required = true)
    protected String paymentReference;

    /**
     * Gets the value of the assignmentDuePaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAssignmentDuePaymentDate() {
        return assignmentDuePaymentDate;
    }

    /**
     * Sets the value of the assignmentDuePaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAssignmentDuePaymentDate(XMLGregorianCalendar value) {
        this.assignmentDuePaymentDate = value;
    }

    /**
     * Gets the value of the assignmentPaymentMeans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentPaymentMeans() {
        return assignmentPaymentMeans;
    }

    /**
     * Sets the value of the assignmentPaymentMeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentPaymentMeans(String value) {
        this.assignmentPaymentMeans = value;
    }

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBAN() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBAN(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the paymentReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentReference() {
        return paymentReference;
    }

    /**
     * Sets the value of the paymentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentReference(String value) {
        this.paymentReference = value;
    }

}
