//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.14 at 05:29:22 p. m. CET 
//


package com.ucm.shiro.facturae.v3_2_2.parser.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CorrectiveType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CorrectiveType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvoiceNumber" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}TextMax20Type" minOccurs="0"/>
 *         &lt;element name="InvoiceSeriesCode" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}TextMax20Type" minOccurs="0"/>
 *         &lt;element name="ReasonCode" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}ReasonCodeType"/>
 *         &lt;element name="ReasonDescription" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}ReasonDescriptionType"/>
 *         &lt;element name="TaxPeriod" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}PeriodDates"/>
 *         &lt;element name="CorrectionMethod" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}CorrectionMethodType"/>
 *         &lt;element name="CorrectionMethodDescription" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}CorrectionMethodDescriptionType"/>
 *         &lt;element name="AdditionalReasonDescription" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}TextMax2500Type" minOccurs="0"/>
 *         &lt;element name="InvoiceIssueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrectiveType", propOrder = {
    "invoiceNumber",
    "invoiceSeriesCode",
    "reasonCode",
    "reasonDescription",
    "taxPeriod",
    "correctionMethod",
    "correctionMethodDescription",
    "additionalReasonDescription",
    "invoiceIssueDate"
})
public class CorrectiveType {

    @XmlElement(name = "InvoiceNumber")
    protected String invoiceNumber;
    @XmlElement(name = "InvoiceSeriesCode")
    protected String invoiceSeriesCode;
    @XmlElement(name = "ReasonCode", required = true)
    protected String reasonCode;
    @XmlElement(name = "ReasonDescription", required = true)
    protected ReasonDescriptionType reasonDescription;
    @XmlElement(name = "TaxPeriod", required = true)
    protected PeriodDates taxPeriod;
    @XmlElement(name = "CorrectionMethod", required = true)
    protected String correctionMethod;
    @XmlElement(name = "CorrectionMethodDescription", required = true)
    protected CorrectionMethodDescriptionType correctionMethodDescription;
    @XmlElement(name = "AdditionalReasonDescription")
    protected String additionalReasonDescription;
    @XmlElement(name = "InvoiceIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceIssueDate;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceSeriesCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceSeriesCode() {
        return invoiceSeriesCode;
    }

    /**
     * Sets the value of the invoiceSeriesCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceSeriesCode(String value) {
        this.invoiceSeriesCode = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the reasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonDescriptionType }
     *     
     */
    public ReasonDescriptionType getReasonDescription() {
        return reasonDescription;
    }

    /**
     * Sets the value of the reasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonDescriptionType }
     *     
     */
    public void setReasonDescription(ReasonDescriptionType value) {
        this.reasonDescription = value;
    }

    /**
     * Gets the value of the taxPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodDates }
     *     
     */
    public PeriodDates getTaxPeriod() {
        return taxPeriod;
    }

    /**
     * Sets the value of the taxPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodDates }
     *     
     */
    public void setTaxPeriod(PeriodDates value) {
        this.taxPeriod = value;
    }

    /**
     * Gets the value of the correctionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrectionMethod() {
        return correctionMethod;
    }

    /**
     * Sets the value of the correctionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrectionMethod(String value) {
        this.correctionMethod = value;
    }

    /**
     * Gets the value of the correctionMethodDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectionMethodDescriptionType }
     *     
     */
    public CorrectionMethodDescriptionType getCorrectionMethodDescription() {
        return correctionMethodDescription;
    }

    /**
     * Sets the value of the correctionMethodDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectionMethodDescriptionType }
     *     
     */
    public void setCorrectionMethodDescription(CorrectionMethodDescriptionType value) {
        this.correctionMethodDescription = value;
    }

    /**
     * Gets the value of the additionalReasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalReasonDescription() {
        return additionalReasonDescription;
    }

    /**
     * Sets the value of the additionalReasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalReasonDescription(String value) {
        this.additionalReasonDescription = value;
    }

    /**
     * Gets the value of the invoiceIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceIssueDate() {
        return invoiceIssueDate;
    }

    /**
     * Sets the value of the invoiceIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceIssueDate(XMLGregorianCalendar value) {
        this.invoiceIssueDate = value;
    }

}
