//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.14 at 05:29:22 p. m. CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml")
package com.ucm.shiro.facturae.v3_2_2.parser.types;
