//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.14 at 05:29:22 p. m. CET 
//


package com.ucm.shiro.facturae.v3_2_2.parser.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentInKindType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentInKindType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentInKindReason" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}TextMax2500Type"/>
 *         &lt;element name="PaymentInKindAmount" type="{http://www.facturae.gob.es/formato/Versiones/Facturaev3_2_2.xml}DoubleUpToEightDecimalType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentInKindType", propOrder = {
    "paymentInKindReason",
    "paymentInKindAmount"
})
public class PaymentInKindType {

    @XmlElement(name = "PaymentInKindReason", required = true)
    protected String paymentInKindReason;
    @XmlElement(name = "PaymentInKindAmount")
    protected double paymentInKindAmount;

    /**
     * Gets the value of the paymentInKindReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentInKindReason() {
        return paymentInKindReason;
    }

    /**
     * Sets the value of the paymentInKindReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentInKindReason(String value) {
        this.paymentInKindReason = value;
    }

    /**
     * Gets the value of the paymentInKindAmount property.
     * 
     */
    public double getPaymentInKindAmount() {
        return paymentInKindAmount;
    }

    /**
     * Sets the value of the paymentInKindAmount property.
     * 
     */
    public void setPaymentInKindAmount(double value) {
        this.paymentInKindAmount = value;
    }

}
