name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Build and run tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Run tests (triggers source compilation)
        run: gradle test
